name: Vless toplist
env:
  TZ: Asia/Pyongyang
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
#  schedule:
#    - cron: '*/15 * * * *'
  workflow_dispatch: # Чтобы ты мог нажать кнопку "Run"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Без этой херни коммиты не полетят!
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: pip install yarl
      - name: Prepare
        run: |
          # Installing sing-box
          curl -o pack.deb -L https://github.com/SagerNet/sing-box/releases/download/v1.13.11/sing-box_1.13.11_linux_amd64.deb
          sudo apt install ./pack.deb
      - name: Do shit
        run: |
          set +e
          # starting fucking tool
          . testloop.sh 

      - name: Git Push
        run: |
          git fetch
          git checkout origin/main
          git reset --soft main
          git switch -C main

          git config --global user.name "Github Action Bot"
          git config --global user.email "actions@github.com"
          git add tested.log topvless64.txt
          LAST_AUTHOR=$(git log -1 --format='%an')
          CMESSAGE="Periodically auto-update _vless [skip ci]"
          if [ "$LAST_AUTHOR" == "Github Action Bot" ]; then
            git commit --amend -m "$CMESSAGE"
            git push --force
          else
            git branch shit @
            # Коммитим только если файл реально изменился
            git diff-index --quiet HEAD || git commit -m "$CMESSAGE"
            git push origin 
            git push -f origin shit
          fi

