name: Node Updater
env:
  TZ: Asia/Pyongyang
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: # Чтобы ты мог нажать кнопку "Run"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Без этой херни коммиты не полетят!
    steps:
      - uses: actions/checkout@v4

      - name: Update File
        run: |
          # Пишем время и маты в файл
          echo "Обновлено: $(date) - ебаная сука" > status.txt
          # Сюда же добавим запуск твоего парсера, когда он будет готов
          python getnfuckit.py

      - name: Git Push
        run: |
          git config --global user.name "Github Action Bot"
          git config --global user.email "actions@github.com"
          git add status.txt sub64.txt log.txt

          # Коммитим только если файл реально изменился
          git diff-index --quiet HEAD || git commit -m "Hourly auto-update [skip ci]"
          git push
